[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "day01"
path = "src/day01.rs"

[[bin]]
name = "day02"
path = "src/day02.rs"

[dependencies]
ferris-says = "0.3.1"

